#index:
#    path: /
#    controller: App\Controller\DefaultController::index
prueba_test:
    path:     /prueba/test
    controller: App\Controller\PruebaController::test
login:
    path:       /
    controller: App\Controller\SecurityController::login
logout:
    path:   /logout
